refactor asset euqueur
wonderwp/Asset pull request #3
Opened 2021-08-19 07:10 UTC by Kevkehz

2021-09-20 13:28 UTC, jdm-web requested changes

2021-09-20 13:28 UTC, jdm-web commented on src/AssetEnqueuerInterface.php
>       * @param array $groupNames
Ajouter en commentaire l'utilité de chaque méthode.

2021-09-20 13:28 UTC, jdm-web commented on src/AssetEnqueuerInterface.php
>       * @param array $groupNames
Ajouter enqueueStyleGroup, enqueueScriptGroup, enqueueStyles, enqueueScripts.

2021-09-20 13:28 UTC, jdm-web commented on src/AssetEnqueuerInterface.php
>       * @param array $groupNames
Créer un objet abstrait qui implémente enqueueStyleGroups, enqueueScriptGroups, enqueueStyles, enqueueScripts, qui ne sont que des boucles qui appellent les méthodes correspondantes au singulier.

2021-09-20 13:28 UTC, jdm-web commented on src/DirectAssetEnqueuer.php
> +    }
Déporter le contenu de la méthode sur le même principe que inline.

2021-09-20 13:28 UTC, jdm-web commented on src/DirectAssetEnqueuer.php
> +        }
Implémenter une méthode findByGroup($groupNzme, $dependencyType) dans l'asset manager.
Utiliser le résultat de cette méthode ici.

2021-09-20 13:28 UTC, jdm-web commented on src/DirectAssetEnqueuer.php
> +        }
Implémenter une méthode findByHandle($handleName, $dependencyType) dans l'asset manager.
Utiliser le résultat de cette méthode ici.

2021-09-20 13:28 UTC, jdm-web commented on src/DirectAssetEnqueuer.php
> +                $this->enqueueScript($dep->handle);
On devrait concaténer ici au lieu d'enqueue.

2021-09-20 13:28 UTC, jdm-web commented on tests/classes/ExampleAssetService.php
> +                new Asset('first-css', '/fixtures/css/first.css', ['styleguide'], null, false, 'first-group'),
Les dépendances styleguide et admin n'existent pas.

2021-09-20 13:28 UTC, jdm-web commented on tests/DirectAssetEnqueurTest.php
> +        $this->wordpressAssetGatewayMock
Ajouter un commentaire de documentation du test.
Qui explique le mock et pourquoi c'est avant.

2021-09-20 13:28 UTC, jdm-web commented on tests/DirectAssetEnqueurTest.php
> +        $enqueur = new DirectAssetEnqueuer($this->assetManager, __DIR__, $this->wordpressAssetGatewayMock);
Déporter la déclaration dans le setup, et utiliser un attribut ensuite pour clarifier le test.

2021-09-20 13:28 UTC, jdm-web commented on tests/DirectAssetEnqueurTest.php
> +    public function testEnqueueScript()
Ajouter la pattern should avec le résultat attendu aux noms des méthodes de test.

2021-09-20 13:28 UTC, jdm-web commented on tests/DirectAssetEnqueurTest.php
> +        $enqueur = new DirectAssetEnqueuer($this->assetManager, __DIR__, $this->wordpressAssetGatewayMock);
Ajouter un petit commentaire sur pourquoi on utilise __DIR__ ici.

2021-09-20 13:28 UTC, jdm-web commented on src/DirectAssetEnqueuer.php
> +                return $this->getAssetContent($dep);
rajouter un filtre autour de $this->getAssetContent($dep) pour qu'on puisse manipuler le contenu de l'inline (minification par ex)

2021-09-20 13:28 UTC, jdm-web commented on tests/DirectAssetEnqueurTest.php
> +}
Manquerait un test Inline Group (css + js)

2021-09-20 13:28 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +    public function __construct(AssetManager $assetManager, $manifestPath, $dest, $prefix, WordpressAssetGateway $wordpressAssetGateway = null)
Documenter les paramètres du constructeur.

2021-09-20 13:28 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +    public function __construct(AssetManager $assetManager, $manifestPath, $dest, $prefix, WordpressAssetGateway $wordpressAssetGateway = null)
Si jamais on a pas besoin de la nuance $prefix, $dest, alors fusionner les deux hors constructeur.

2021-09-20 13:28 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +
Essayer de nettoyer le constructeur, concernant surtout l'utilisation de dest, prefix, blogurl.
Essayre de voir si on peut les lire à partir de manifest, ou si on les passes depuis l'exterieur.

2021-09-20 13:28 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +                $this->wordpressAssetGateway->registerStyle($group, $src, [], null);
Le tableau des dépendances ne devrait pas forcément être vide.
Est-mieux le lire les dépendances dans l'assets manager ? ou des les écrire dans le manifest assets.json.

2021-09-20 13:28 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +            if (file_exists($src) && !$this->wordpressAssetGateway->isAdmin()) {
C'est forcément une opinion wdf ça, à enlever du niveau framework.
```suggestion
            if (file_exists($src)) {
```

2021-09-20 13:28 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +                return $this->wordpressAssetGateway->applyFilters('wwp.enqueur.critical.css.content', file_get_contents($src));
```suggestion
                return $this->wordpressAssetGateway->applyFilters('wwp.enqueur.inline.css.content', file_get_contents($src),$handle);
```

2021-09-20 13:28 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +                return $this->wordpressAssetGateway->applyFilters('wwp.enqueur.critical.js.content', file_get_contents($src));
```suggestion
                return $this->wordpressAssetGateway->applyFilters('wwp.enqueur.inline.js.content', file_get_contents($src),$handle);
```

2021-09-20 13:28 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +    protected function isPropertyExistInManifest(string $type, string $group)
```suggestion
    protected function doesPropertyExistInManifest(string $type, string $group)
```

2021-09-20 13:28 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +    protected function getUrlSrcFrom(string $type, string $group)
```suggestion
    protected function getUrlFrom(string $type, string $group)
```

2021-09-20 13:28 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +    protected function getPathSrcFrom(string $type, string $group)
```suggestion
    protected function getPathFrom(string $type, string $group)
```

2021-09-20 13:28 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +        return $_SERVER['DOCUMENT_ROOT'] . str_replace($this->prefix, '', $path);
Peut poser le pbm en ligne de commande.
Est-ce qu'on passerait pas cette valeur depuis l'extérieur ?

2021-09-20 13:28 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +                $this->wordpressAssetGateway->registerScript($group, $src, $dependencies, null, true);
Ici construire un tableau plutôt que de faire l'action.
Ensuite on expose ce tableau à un filtre
puis on boucle sur ce tableau pour faire le registerScript.
On utilisera ce filtre pour injecter vendor.
Idem pour les CSS.
On pourra ainsi supprimer les lignes 55 à 59

2021-09-20 13:28 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +    }
Devrait sauter de cet objet si on injecte vendor via un filtre.

2021-09-20 13:28 UTC, jdm-web commented on tests/JsonAssetEnqueurTest.php
> +        $_SERVER['DOCUMENT_ROOT'] = __DIR__;
A voir si on en a encore besoin.

2021-09-20 13:28 UTC, jdm-web commented on tests/JsonAssetEnqueurTest.php
> +        $enqueuer = new JsonAssetEnqueuer($this->assetManager, __DIR__ . '/fixtures/assets.json', '/fixtures/dist', '', $this->wordpressAssetGatewayMock);
Déporter la déclaration dans le setup

2021-09-20 13:28 UTC, jdm-web commented on tests/classes/PackageAssetService.php
> +<?php
Voir si on peut supprimer ce fichier, ou si les groupes sont importants.

2021-09-20 14:18 UTC, hostekevin commented on src/DirectAssetEnqueuer.php
> +        }
En fait il y a deux méthodes qui font déjà ça : `getDependenciesFromGroup($groupName, $dependencyType)` et `getDependency($dependencyType, $handle)`

2021-09-20 14:20 UTC, Kevkehz commented on src/DirectAssetEnqueuer.php
> +    }
Après vérification, on ne peut pas vraiment faire ça. Dans le cas d'inline cela fonctionne bien car la seul différence entre le css et js c'est le type de dépendance, alors que pour les enqueues, il faut aussi appeler une méthode différente: `enqueueStyle` et `enqueueScript`

2021-09-20 14:20 UTC, Kevkehz commented on src/DirectAssetEnqueuer.php
> +        }
J'ai utilisé la méthode déjà implémentée : `getDependency($dependencyType, $handle)`

2021-09-21 14:09 UTC, jdm-web requested changes

2021-09-21 14:09 UTC, jdm-web commented on src/AbstractAssetEnqueuer.php
> +    public $assetManager;
public ? C'est rare d'avoir un objet comme ça public non ? On en a besoin ou c'est un oubli ?
On pourrait aussi typer en commentaire.

2021-09-21 14:09 UTC, jdm-web commented on src/DirectAssetEnqueuer.php
> +    private function register()
Ajoutons un commentaire d'explication de la méthode.

2021-09-21 14:09 UTC, jdm-web commented on src/DirectAssetEnqueuer.php
> +        $toRender = $this->assetManager->getDependencies('css');
```suggestion
        $cssToRegister = $this->assetManager->getDependencies('css');
```

2021-09-21 14:09 UTC, jdm-web commented on src/DirectAssetEnqueuer.php
> +        $toRender = $this->assetManager->getDependencies('js');
```suggestion
        $jsToRegister = $this->assetManager->getDependencies('js');
```

2021-09-21 14:09 UTC, jdm-web commented on src/DirectAssetEnqueuer.php
> +        $toRender = $this->assetManager->getDependenciesFromGroup($groupName, 'css');
```suggestion
        $toEnqueue = $this->assetManager->getDependenciesFromGroup($groupName, 'css');
```

2021-09-21 14:09 UTC, jdm-web commented on src/DirectAssetEnqueuer.php
> +        $toRender = $this->assetManager->getDependenciesFromGroup($groupName, 'js');
```suggestion
        $toEnqueue = $this->assetManager->getDependenciesFromGroup($groupName, 'js');
```

2021-09-21 14:09 UTC, jdm-web commented on src/DirectAssetEnqueuer.php
> +        $toRender = $this->assetManager->getDependenciesFromGroup($groupName, 'css');
```suggestion
        $toInline = $this->assetManager->getDependenciesFromGroup($groupName, 'css');
```

2021-09-21 14:09 UTC, jdm-web commented on src/DirectAssetEnqueuer.php
> +        $toRender = $this->assetManager->getDependenciesFromGroup($groupName, 'js');
```suggestion
        $toInline = $this->assetManager->getDependenciesFromGroup($groupName, 'js');
```

2021-09-21 14:09 UTC, jdm-web commented on src/DirectAssetEnqueuer.php
> +            return file_get_contents($dep->src);
Idéalement il faudrait qu'on s'appuie sur WP_Filesystem plutôt que de faire ça en direct.
A voir comment on peut l'intégrer dans cette classe (passage en constructeur peut-être).

2021-09-21 14:09 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +
Avions-nous besoin de tout alors au final ?

2021-09-21 14:09 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +        $cssAssets = $this->wordpressAssetGateway->applyFilters('wwp.JsonAssetsEnqueur.register.cssAssets', $cssAssets);
Je me dis qu'on devrait appliquer le même système au direct asset enqueur non ?

2021-09-21 14:09 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +                $cssAssets[] = [
Ne devrions-nous pas ajouter une clé claire à cet élément de tableau afin de pouvoir le cibler plus efficacement si on manipule le tableau avec le filtre ?

2021-09-21 14:09 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +    private function registerScripts(): void
Mêmes commentaires que pour les CSS.

2021-09-21 14:09 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +                return $this->wordpressAssetGateway->applyFilters('wwp.enqueur.inline.css.content', file_get_contents($src));
Idem que commentaire sur WP_Filesystem

2021-09-21 14:09 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +    public function getVersion(): ?int
Elle est vraiment dogmatique cette méthode quand même.
On en rediscute ensemble.

2021-09-21 14:09 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +    protected function isPropertyExistInManifest(string $type, string $group): bool
```suggestion
    protected function doesPropertyExistInManifest(string $type, string $group): bool
```

2021-09-21 14:09 UTC, jdm-web commented on tests/classes/ExampleAssetService.php
> +                new Asset('second-css', '/fixtures/css/second.css', ['first-css'], null, false, 'styleguide'),
Le test serait plus frappant si jamais second-css avait third-css en dépendance.

2021-09-21 14:42 UTC, Kevkehz commented on src/JsonAssetEnqueuer.php
> +
En soit le résultat de `get_blog_url()` semble faire le même job, c'est ce qu'on va recevoir ici en paramètre

2021-09-21 15:10 UTC, hostekevin commented on src/JsonAssetEnqueuer.php
> +                $this->wordpressAssetGateway->registerStyle($group, $src, [], null);
Il faudrait créer une clé `cssDependencies` dans l'`JsonAssetExporter`. Cela éviterait de calculer systématiquement les dépendances.

2021-09-21 15:32 UTC, Kevkehz commented on src/JsonAssetEnqueuer.php
> +        $cssAssets = $this->wordpressAssetGateway->applyFilters('wwp.JsonAssetsEnqueur.register.cssAssets', $cssAssets);
ok c'est fait

2021-09-21 15:33 UTC, hostekevin commented on src/JsonAssetEnqueuer.php
> +                $cssAssets[] = [
J'ai rajouté le `$handle` en clé

2021-09-22 09:39 UTC, jdm-web requested changes

2021-09-22 09:39 UTC, jdm-web commented on src/DirectAssetEnqueuer.php
> +     * Make js/css available to be able to queue them later
```suggestion
     * Make js/css known to WordPress to be able to enqueue them more easily later on
```

2021-09-22 09:39 UTC, jdm-web commented on src/DirectAssetEnqueuer.php
> +        $cssToRegister = $this->wordpressAssetGateway->applyFilters('wwp.enqueuer.register.cssAssets', $cssToRegister);
Vu que le filtre a le même nom partout (ce qui me semble juste), il faudrait qu'on passe l'enqueur en param si jamais on avait envie de faire des traitements différents en fonction du contexte d'enqueue.

```suggestion
        $cssToRegister = $this->wordpressAssetGateway->applyFilters('wwp.enqueuer.register.cssAssets', $cssToRegister,$this);
```

2021-09-22 09:39 UTC, jdm-web commented on src/DirectAssetEnqueuer.php
> +        $jsToRegister = $this->wordpressAssetGateway->applyFilters('wwp.enqueuer.register.jsAssets', $jsToRegister);
```suggestion
        $jsToRegister = $this->wordpressAssetGateway->applyFilters('wwp.enqueuer.register.jsAssets', $jsToRegister,$this);
```

2021-09-22 09:39 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +        $this->blogUrl = $this->wordpressAssetGateway->applyFilters('wwp.enqueuer.blogUrl', $blogUrl);
Je n'ai pas l'impression que l'on retrouve ce filtre dans tous les enqueurs, du coup il faudrait probablement préciser son nom (wwp.JsonAssetEnqueuer.blogUrl).
Si on le retrouve à plusieurs endroits, alors on garde un nom générique et on passe l'enqueuer en 2nd param du filtre.

2021-09-22 09:39 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +        $cssToRegister = $this->wordpressAssetGateway->applyFilters('wwp.enqueuer.register.cssAssets', $cssToRegister);
```suggestion
        $cssToRegister = $this->wordpressAssetGateway->applyFilters('wwp.enqueuer.register.cssAssets', $cssToRegister,$this);
```

2021-09-22 09:39 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +        $jsToRegister = $this->wordpressAssetGateway->applyFilters('wwp.enqueuer.register.jsAssets', $jsToRegister);
```suggestion
        $jsToRegister = $this->wordpressAssetGateway->applyFilters('wwp.enqueuer.register.jsAssets', $jsToRegister,$this);
```

2021-09-22 09:39 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +                // Todo: faire la vérification !is_admin() dans le filtre
Certes, mais ce n'est pas un commentaire à garder ici.

```suggestion
```

2021-09-22 09:54 UTC, jdm-web requested changes

2021-09-22 09:54 UTC, jdm-web commented on src/DirectAssetEnqueuer.php
> +    public function __construct(AssetManager $assetManager, string $publicPath, WordpressAssetGateway $wordpressAssetGateway = null)
Donner la possibilité de passer / stocker un WP_Filesystem en 4eme param.
Si null -> instancier un WP_Filesystem_Direct
Utiliser les méthodes sur le filesystem plutôt que les méthodes PHP en dur.
Idem sur le json enqueur.

2021-09-22 16:47 UTC, jdm-web requested changes

2021-09-22 16:47 UTC, jdm-web commented on src/AbstractAssetEnqueuer.php
> +    public function __construct(AssetManager $assetManager, $filesystem)
garder uniquement l'asset manager, et redescendre le file system dans les enfants qui en ont besoin.

2021-09-22 16:47 UTC, jdm-web commented on src/AssetManager.php
> +    public function getDistinctGroups(string $dependencyType) {
```suggestion
    public function getDistinctGroupsDependencies(string $dependencyType) {
```
+ ajouter un commentaire.

2021-09-22 16:47 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +            throw new \Exception('File manifest does not exist');
Créer une MissingJsonManifestException et passer le chemin vers le manifest dans le message d'erreur afin que ça soit utile pour le developpeur.

2021-09-22 16:47 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +    public function getVersion(): ?int
Passer le numéro de version dans le constructeur.

2021-09-22 16:47 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +        return $this->manifest->site->assets_dest . '/' . $type . '/' . $group . $this->getVersion() . '.' . $type;
remplacer les / par des DIRECTORY_SEPARATOR

2021-09-22 16:47 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +        return $this->manifest->site->assets_dest . '/' . $type . '/' . $group . $this->getVersion() . '.' . $type;
Pouvoir utiliser une pattern SrcPattern qui établi des wildcards, qui seront search / replace par des vraies valeurs.

2021-09-22 16:47 UTC, jdm-web commented on src/AssetPackage.php
> +        }
Ca fait beaucoup de logique dans le constructeur, je déporterais ça dans une méthode spécifique.

2021-09-22 16:47 UTC, jdm-web commented on src/AssetPackage.php
> +            $containOnlyAuthorizedGroups = !count(array_diff($opts['assetTypes'], $this->availableAssetTypes));
Semble dogmatique. Peut-être faut-il passer les availableAssetTypes en constructeur ?

2021-09-22 16:47 UTC, jdm-web commented on src/AssetPackage.php
> +                throw new LogicException('You must provide asset group according to available groups : ' . join(', ', $this->availableAssetTypes));
Créons  une exception exprès.

2021-09-22 16:47 UTC, jdm-web commented on src/PackageAssetEnqueuer.php
> +        foreach ($this->packages->getPackagesBy('critical') as $package) {
On a de l'opinion qui traine ici.

2021-09-22 16:47 UTC, jdm-web commented on src/PackageAssetEnqueuer.php
> +        return $group . '_wwp_' . $package->getName();
Pourquoi est-ce nécessaire?

2021-09-23 08:37 UTC, jdm-web requested changes

2021-09-23 08:37 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +        int $version,
ne pas typer la version au cas où .

2021-09-23 08:37 UTC, jdm-web commented on src/PackageAssetEnqueuer.php
> +                $this->wordpressAssetGateway->registerStyle(
Uniformiser sur le modèle des 2 autres enqueurs. (Ajouter un filtre, création d'un talbeau intermédiaire qu'on puisse manipuler par filtre).

2021-09-23 08:37 UTC, jdm-web commented on src/PackageAssetEnqueuer.php
> +                $this->wordpressAssetGateway->registerScript(
Uniformiser sur le modèle des 2 autres enqueurs. (Ajouter un filtre, création d'un talbeau intermédiaire qu'on puisse manipuler par filtre).

2021-09-23 14:23 UTC, jdm-web requested changes

2021-09-23 14:23 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +    public function getVersion(): ?int
On peut supprimer la logique de cette méthode.
A voir si on doit garder le getter.

2021-09-23 14:23 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +        return $this->manifest->site->assets_dest . '/' . $type . '/' . $group . $this->getVersion() . '.' . $type;
Exemple de SrcPattern : {assets_dest}/{type}/{group}{version}.{type}
$search = [
 {assets_dest},
{type},
{group},
{version}
];
$replace = [
$this->manifest->site->assets_dest,
$type,
$group,
$version
];
return str_replace($search,$replace,$srcPattern);

2021-09-24 09:52 UTC, jdm-web requested changes

2021-09-24 09:52 UTC, jdm-web commented on src/AssetPackage.php
> +    }
On aurait pas intérêt à garder $opts en tant qu'attribut de l'objet ?

2021-09-24 09:52 UTC, jdm-web commented on src/AssetPackages.php
> +        if (null === $name) {
Il existe une fonction is_null en php je crois.
```suggestion
        if (is_null($name)) {
```
idem pour la ligne suivante.

2021-09-24 09:52 UTC, jdm-web commented on src/AssetPackages.php
> +    private $packages = [];
```suggestion
    /**  @var PackageInterface|null */
    private $defaultPackage;
    /** @var Package[] **/
    private $packages = [];
```

2021-09-24 09:52 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +        if ($wordpressAssetGateway === null) {
```suggestion
        if (is_null($wordpressAssetGateway)) {
```

2021-09-24 09:52 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +        $this->assetManager->callServices();
```suggestion
       //Building up complete asset vision thanks to asset services
        $this->assetManager->callServices();
```

2021-09-24 09:52 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +        switch ($dependencyType) {
Je changerais bien de design pattern ici.
Je verrais plutôt une utilisation par sous méthode qu'un switch.
Cf la méthode newRelation de ModelForm (https://github.com/agencewonderful/wonderwp-plugin/blob/develop/includes/Framework/Form/ModelForm.php#L186-L198)
Ca permet notamment de créer de nouvelles méthodes dans une classe enfant sans devoir overrider computeDependencyArray pour rajouter un case au switch.

2021-09-24 09:52 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +        if ($asset) {
-
```suggestion
        //This enqueur works with groups, not individual files, hence retrieving the group from the file first, then enqueuing the group file.
        if ($asset) {
```

2021-09-24 09:52 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +        if ($asset) {
```suggestion
        //This enqueur works with groups, not individual files, hence retrieving the group from the file first, then enqueuing the group file.
        if ($asset) {
```

2021-09-24 09:52 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +        if ($asset) {
//This enqueur works with groups, not individual files, hence retrieving the group from the file first, then inlining the group file.```suggestion
        if ($asset) {
```

2021-09-24 09:52 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +        if ($asset) {
```suggestion
    //This enqueur works with groups, not individual files, hence retrieving the group from the file first, then inlining the group file.```suggestion

        if ($asset) {
```

2021-09-24 09:52 UTC, jdm-web commented on src/JsonAssetEnqueuer.php
> +        return str_replace($search, $replace, $pattern);
Alors techniquement c'est ça, mais l'intérêt de tout ça c'est de piloter $pattern en fait.
Soit en attribut statique privé, soit en param constructeur.

2021-09-24 09:52 UTC, jdm-web commented on src/PackageAssetEnqueuer.php
> +        if ($wordpressAssetGateway === null) {
```suggestion
        if (is_null($wordpressAssetGateway)) {
```

2021-09-24 09:52 UTC, jdm-web commented on src/PackageAssetEnqueuer.php
> +        $this->assetManager->callServices();
```suggestion
       //Building up complete asset vision thanks to asset services
        $this->assetManager->callServices();
```

2021-09-24 09:52 UTC, jdm-web commented on src/PackageAssetEnqueuer.php
> +        if ($asset) {
```suggestion
        //This enqueur works with groups, not individual files, hence retrieving the group from the file first, then enqueuing the group file.
        if ($asset) {
```

2021-09-24 09:52 UTC, jdm-web commented on src/PackageAssetEnqueuer.php
> +        if ($asset) {
```suggestion
        //This enqueur works with groups, not individual files, hence retrieving the group from the file first, then enqueuing the group file.
        if ($asset) {
```

2021-09-24 09:52 UTC, jdm-web commented on src/PackageAssetEnqueuer.php
> +        if ($asset) {
```suggestion
        //This enqueur works with groups, not individual files, hence retrieving the group from the file first, then inlining the group file.
        if ($asset) {
```

2021-09-24 09:52 UTC, jdm-web commented on src/PackageAssetEnqueuer.php
> +        if ($asset) {
```suggestion
        //This enqueur works with groups, not individual files, hence retrieving the group from the file first, then inlining the group file.
        if ($asset) {
```

2021-09-28 09:37 UTC, merged